import "./globals.css";
import {Outfit} from "next/font/google";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Simplify Notes",
  description: "Generated by Simplify Notes",
  icons: {
    icon: '/icon.png', 
  },
};

const outfit= Outfit({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
     <html lang="en">
      <body
       className={outfit.className}
       suppressHydrationWarning={true} 
       >
        <Provider>
          {children}
        </Provider>
        <Toaster/>
      </body>
     </html>
    </ClerkProvider>
  )
}
